# Generated by Django 4.0.4 on 2022-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_currentaccount_foreignaccount_savingsaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='account_number',
            field=models.CharField(max_length=28, unique=True),
        ),
        migrations.AlterField(
            model_name='foreignaccount',
            name='account_number',
            field=models.CharField(max_length=28, unique=True),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_number',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
