# Generated by Django 4.0.4 on 2022-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0005_alter_currentaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignaccount',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.FloatField(),
        ),
    ]
