# Generated by Django 4.0.4 on 2022-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0006_alter_foreignaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='type',
            field=models.CharField(default='Current', max_length=30),
        ),
        migrations.AlterField(
            model_name='foreignaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
