# Generated by Django 4.0.4 on 2022-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0007_alter_currentaccount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignaccount',
            name='type',
            field=models.CharField(default='Foreign', max_length=30),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='type',
            field=models.CharField(default='Savings', max_length=30),
        ),
    ]
